### ISSUE TITLE
upcoming sf will break slga

### ISSUE THREAD

**Issue by edzer** [obrl-soil/slga#1]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html and
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

most likely you have a legacy `sf` object in the package, e.g. for examples, which has the old `crs` structure and breaks upstream code. Let me know when you need help to sort this out.

**Comment by obrl-soil** [comment]
Thanks Edzer, this'll be a weekend project :)

**Comment by rsbivand** [comment]
Seems to be resolved with 1.1.1 - great work!
