### ISSUE TITLE
problem with datum definition PROJ deprecated in favour of WKT

### ISSUE THREAD

**Issue by DavidHine** [obrl-soil/slga#2]
Thanks for creating the SLGA package. 
In running it and using the vignette as a guide, I found that a command failed due to the use, it seems, of PROJ definitions. The command and response are below
_aoi <- c(152.95, -27.55, 153.07, -27.45)
> bne_surface_clay <- get_soils_data(product = 'NAT', attribute = 'CLY',
+                                    component = 'ALL', depth = 1,
+                                    aoi = aoi, write_out = FALSE)
Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition,
 but +towgs84= values preserved_
There were 6 of the warning messages, all duplicates of this one.
In searching for a solution I found a discussion about the issue and an RFC started in Oct 2019. It can be found here https://rdrr.io/rforge/rgdal/f/vignettes/PROJ6_GDAL3.Rmd 
Package sp gets attention in the discussion.

**Comment by lauren-obrien** [comment]
Hi David, can you please report the OS you're using, plus the versions of PROJ and GDAL R reports when you load `sf`?

**Comment by obrl-soil** [comment]
Hi David, can you please report the OS you're using, plus the versions of PROJ and GDAL R reports when you load `sf`?

**Comment by DavidHine** [comment]
Hi Lauren,
I am using Ubuntu 20.04. 
When loading sf, I get:
library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

**Comment by obrl-soil** [comment]
Hmm ok. are you able to update past PROJ 6.3.1? I'm getting no errors on Ubuntu 18.04 with PROJ 7.0.0. I think there was some funny stuff happening as PROJ moved through the 6.x releases.

**Comment by obrl-soil** [comment]
Assuming this is resolved due to lack of further contact.
