### ISSUE TITLE
Failed to install on Google Colab

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [obrl-soil/slga#3]
Hi, I tried to install the package on Google Colab (Jupiter notebook) but it did not work. Seems like it failed to install a bunch of dependencies

R[write to console]: Error in library(slga) : there is no package called ‘slga’
Calls: <Anonymous> -> <Anonymous> -> withVisible -> library

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘units’ had non-zero exit status

R[write to console]: 2: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘sf’ had non-zero exit status

R[write to console]: 3: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘slga’ had non-zero exit status

R[write to console]: 4: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘units’ had non-zero exit status

R[write to console]: 5: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘sf’ had non-zero exit status

R[write to console]: 6: 
R[write to console]: In install.packages("slga") :
R[write to console]: 
 
R[write to console]:  installation of package ‘slga’ had non-zero exit status

Error in library(slga) : there is no package called ‘slga’
Calls: <Anonymous> -> <Anonymous> -> withVisible -> library

**Comment by obrl-soil** [comment]
Hmm, can't say I've ever tried that platform, thought it was Py only. Maybe you have to manually install the dependencies first?

**Comment by Daniel-Trung-Nguyen** [comment]
Got it figured out. Basically, some dev tools need to be installed first using the command below.
# Install/update dev kits (this helps install sf and units libraries)
!apt-get -y update && apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev
