### ISSUE TITLE
could not find function "get_slga_data"

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [obrl-soil/slga#4]
The  "get_slga_data" example on your git page does not seem to work anymore
Error in get_slga_data(product = "NAT", attribute = "CLY", component = "all",  : 
  could not find function "get_slga_data"

**Comment by JodyBig** [comment]
I also have the same problem.

> The "get_slga_data" example on your git page does not seem to work anymore
> Error in get_slga_data(product = "NAT", attribute = "CLY", component = "all", :
> could not find function "get_slga_data"

**Comment by obrl-soil** [comment]
Whoops, typed the wrong function name in the readme 🙃. Fixed with commit bccc881. Thanks for reporting.
