### ISSUE TITLE
upcoming sf will break slga when using s2

### ISSUE THREAD

**Issue by edzer** [obrl-soil/slga#6]
Hi Lauren! Please see https://github.com/r-spatial/sf/issues/1649 and consider commenting there in case this is not trivial to solve. Many regards,

**Comment by obrl-soil** [comment]
Thanks Edzer. I'm getting some inconsistent results with `st_intersection()` when s2 is active:

```
library(sf)

tile <- structure(c(140.999583, -10.500417, 141.999583, -9.500417), 
                  names = c("xmin", "ymin", "xmax", "ymax"),
                  class = "bbox", crs =  sf::st_crs(4283))

ext <- structure(c(112.99958, -44.00042, 153.99958, -10.00125), 
                 names = c("xmin", "ymin", "xmax", "ymax"),
                 class = "bbox", crs =  sf::st_crs(4283))

sf_use_s2(FALSE)
st_intersects(st_as_sfc(tile), st_as_sfc(ext))

sf_use_s2(TRUE)
st_intersects(st_as_sfc(tile), st_as_sfc(ext))

```

`tile` should partially overlap `ext` in both cases, and by a good 50km. Not sure how to apply s2 options to ensure consistent behaviour. Is this about detail level somehow?

**Comment by edzer** [comment]
"Should" is in the eye of the beholder: for `s2`, "lines" between points are always great circles, not lines in plate carree; try e.g. an orthographic view centered on your area which shows this better:
```r
g = c(st_as_sfc(tile), st_as_sfc(ext))
st_crs(g) = 4326
plot(st_transform(g, "+proj=ortho +lon_0=140 +lat_0=-20"),axes=T)
```
![x](https://user-images.githubusercontent.com/520851/115953905-824a2100-a4ee-11eb-93a6-bfe751a728ac.png)

If you need to continue working in plate carree, then make it plate carree, e.g. by transforming to ["+proj=eqc"](https://proj.org/operations/projections/eqc.html) or reset the CRS to `NA`.

**Comment by obrl-soil** [comment]
coming back to this a bit late - are you saying the intersection will return the correct results with s2 enabled if both bboxes lack a CRS? I can roll with that but it looks like there might be a missing method for setting crs's on bbox objects - `sf::st_crs(aoi) <- NA` does not work, nor does `sf::st_transform(aoi, NA)`. 

Looks like I have to loop through turning an AOI back into a polygon before removing projection information and re-extracting the bbox. Is that intended?

**Comment by edzer** [comment]
You are right, a `st_crs<-` method for `bbox` is lacking, I will add that. Right now you'd have to do
```
st_as_sfc(structure(ext, crs = st_crs(NA)))
```

**Comment by obrl-soil** [comment]
Ah cool, thanks :) what I've sent to CRAN will do for now, I'll refine it after the next sf release.

https://github.com/obrl-soil/slga/blob/8e306f97eb6826efb257eba3e341aac836198110/R/aoi_processing.R#L134-L138
