### ISSUE TITLE
write_out and Reso

### ISSUE THREAD

**Issue by inespereda** [obrl-soil/slga#7]
Hey! amazing tool, it reduces heaps amount of work. However, although I set the file in write_out, it does not print them into the folder. I've set the directory to the same folder + the path in write_out. 

landscape_var <- lapply(c("MRVBF","PLNCV","PRFCV"), function(t){
  get_lscape_data(product = t, aoi = extent, write_out = "Y:/Projects/sIS/14_Enviro_Variables/WGS")
})

Also, is there any way of choosing the resolution, the package downloads at 83 m but we would like to have access to the 30m as well. 

Cheers!

**Comment by obrl-soil** [comment]
Hi,

you have to set `write_out = TRUE` and then specify a directory as `filedir = 'Y:/etc'`, per the tool documentation.

Unfortunately the 30m versions of the terrain datasets have not been made part of the WCS service that this package taps into; those are only available from the CSIRO DAP. The soils layers were only ever modelled at 90m/1", but future updates may be at a finer resolution.
